---
openapi: "3.0.0"
info:
  title: "Pizza Store Server"
  version: "1.0.0"
  description: "This is a APIs of Pizza Store Server."
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: Product
  - name: Order
  - name: Auth
  - name: User
  - name: Store
  - name: Report
paths:
  #-----------Product--------------------------------------------------------------------------------------------------------------------------------
  /products:
    get:
      tags:
        - Product
      summary: Get products information
      parameters:
        - $ref: "#/components/parameters/page"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/category"
      responses:
        200:
          description: "Successful operation"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Products"
        500:
          description: Internal Server Error
      security:
        - BearerAuth: []
    post:
      tags:
        - Product
      summary: "Create new product"
      requestBody:
        content:
          multipart/form-data:
            schema:
              allOf:
                - $ref: "#/components/schemas/CreateProductBody"
                - type: object
        description: "Created new product"
        required: true
      responses:
        default:
          description: "Successful operation"
  /products/{id}:
    get:
      tags:
        - Product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64

      responses:
        "200":
          description: successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
            application/xml:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          description: Invalid ID supplied
        "404":
          description: Product not found

  #-----------Order--------------------------------------------------------------------------------------------------------------------------------

  #-----------Auth--------------------------------------------------------------------------------------------------------------------------------
  /auth/login:
    post:
      summary: Login account 
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Login"
      responses:
        '200':
          description: Login success
  /auth/logout:
    post:
      summary: Logout account
      tags:
        - Auth
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Logout success
  /auth/register:
    post:
      summary: Register account
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Register"
      responses:
        '201':
          description: Created
  /auth/forgot-password:
    post:
      summary: Reset password
      tags:
        - Auth
      requestBody:
        require: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_email:
                  type: string
              example:
                user_email: tanvo9927@gmail.com
      responses:
        '200':
          description: Reset password sucess

  #-----------User--------------------------------------------------------------------------------------------------------------------------------
  /users/me:
    get:
      summary: Get account profile
      tags:
        - User
      security:
        - BearerAuth: []
      responses:
        '200':
          description: "OK"
    patch:
      summary: Modify profile
      tags:
        - User
      security:
        - BearerAuth: []
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ModifyProfile"
      responses:
        '200':
          description: "OK"
  /users:
    get:
      summary: Get all account profile
      tags:
        - User
      security:
        - BearerAuth: []
      responses:
        '200':
          description: "OK"
  /users/change-role:
    patch:
      summary: Change role
      tags:
        - User
      security:
        - BearerAuth: []
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangeRole"
      responses:
        '200':
          description: "OK"          
  /users/change-password:
    patch:
      summary: Change password
      tags:
        - User
      security:
        - BearerAuth: []
      requestBody:
        require: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePassword"
      responses:
        '200':
          description: "OK"

  #-----------Store--------------------------------------------------------------------------------------------------------------------------------

  #-----------Report--------------------------------------------------------------------------------------------------------------------------------

components:
  #------------------------------------------------------------------#
  schemas:
    ##------------------------
    Product:
      $ref: "./components/schemas/product.yml#/Product"
    Products:
      $ref: "./components/schemas/product.yml#/Products"
    CreateProductBody:
      $ref: "./components/schemas/product.yml#/CreateProductBody"

    ##------------------------
    Login:
      $ref: "components/schemas/auth.yml#/Login"
    Register:
      $ref: "components/schemas/auth.yml#/Register"

    ##------------------------
    ModifyProfile:
      $ref: "components/schemas/user.yml#/ModifyProfile"
    ChangeRole:
      $ref: "components/schemas/user.yml#/ChangeRole"
    ChangePassword:
      $ref: "components/schemas/user.yml#/ChangePassword"

  #------------------------------------------------------------------#
  parameters:
    page:
      $ref: "./components/parameters/general-parameter.yml#/page"
    limit:
      $ref: "./components/parameters/general-parameter.yml#/limit"
    category:
      $ref: "./components/parameters/general-parameter.yml#/category"
  #------------------------------------------------------------------#
  #------------------------------------------------------------------#
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  #------------------------------------------------------------------#
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
externalDocs:
  description: "More details"
  url: "http://swagger.io"
