Products:
  type: array
  items:
    $ref: "#/Product"

Product:
  type: object
  properties:
    product_id:
      type: integer
      format: int64
      example: 10
    product_name:
      type: string
      example: Cheese pizza
    product_slug:
      type: string
      example: cheese-pizza
    product_desc:
      type: string
    category:
      type: string
      enum:
        - Food
        - Drink
        - Topping
    url_image:
      type: string
      example: https://res.cloudinary.com/de6z1fqfs/image/upload/v1700031086/pizzaTop/products/pizzaCheese_fdgs47.jpg
    sizes:
      type: array
      items:
        $ref: "#/ProductSize"

ProductSize:
  type: object
  properties:
    size_name:
      type: string
      example: Small
    product_price:
      type: float
      example: 100000.00

CreateProductBody:
  type: object
  properties:
    productName:
      type: string
    productDesc:
      type: string
    productImage:
      type: string
      format: binary
# GeneralCourse:
#   allOf:
#     - $ref: "#/Course"
#     - type: object
#       properties:
#         userCourseStatus:
#           type: "string"
#           enum: [NOT_REGISTER, PENDING]
#           description: >
#             Explanations: <br>
#             * `NOT_REGISTER` - user not register this course yet. <br>
#             * `PENDING` - user is waiting for approval to join this course.

# PersonalCourse:
#   allOf:
#     - $ref: "#/Course"
#     - type: object
#       properties:
#         userCourseProcess:
#           type: integer
#           maximum: 100
#           minimum: 0
#   example:
#     name: Tieng anh 6
#     duration: 1800
#     members: 50
#     authors: Duy Vu
#     courseImageUrl: 'https://123.com'
#     userCourseProcess: 85

# CoursesResponse:
#   type: array
#   items:
#     type: object
#     properties:
#       tagName:
#         type: string
#         enum: [POPULAR, BY-USER, NEWEST, ALL]
#       result:
#         type: array
#         items:
#           oneOf:
#             - $ref: "#/GeneralCourse"
#             - $ref: "#/PersonalCourse"

# CourseDetails:
#   type: object
#   properties:
#     id:
#       type: number
#     name:
#       type: string
#     title:
#       type: string
#     description:
#       type: string
#     acceptanceScore:
#       type: number
#     lessons:
#       type: array
#       items:
#         $ref: "./lesson.yml#/Lesson"
#   example:
#     id: 1
#     name: Tieng anh lop 6
#     title: null
#     shortMessage: Nang cao von tu moi ngay ban nhe
#     description: Khóa học tiếng anh lớp 6 giúp trẻ xây dựng 4 kỹ năng - Phát triển tư tuy phản biện tốt. Giáo trình đạt chuẫn Mỹ - Được biên soạn sát với học viên giúp bé tự tin và nắm bắt tốt. Rèn luyện 4 kỹ năng. Ngoại khóa phong phú.
#     acceptanceScore: 70
#     lessons:
#       - id: 1
#         name: Unit1 My new school,
#         lessonImageUrl: https://image.com,
#         fileId: null,
#         lessonDesc: This unit includes
#         shortMessage: First day of school! Wake up! Please. First day of school,
#         status: LEARNING
#         currentProcess: 80
#       - id: 2
#         name: Unit1 My new school,
#         lessonImageUrl: https://image.com,
#         fileId: null,
#         lessonDesc: This unit includes
#         shortMessage: First day of school! Wake up! Please. First day of school,
#         status: OPEN
#         currentProcess: 0
#       - id: 3
#         name: Unit1 My new school,
#         lessonImageUrl: https://image.com,
#         fileId: null,
#         lessonDesc: This unit includes
#         shortMessage: First day of school! Wake up! Please. First day of school,
#         status: LOCKED
#         currentProcess: 0
