Products:
  type: array
  items:
    $ref: "#/Product"

Product:
  type: object
  properties:
    product_id:
      type: integer
      format: int64
      example: 10
    product_name:
      type: string
      example: Cheese pizza
    product_slug:
      type: string
      example: cheese-pizza
    product_desc:
      type: string
    category:
      type: string
      enum:
        - Food
        - Drink
        - Topping
    url_image:
      type: string
      example: https://res.cloudinary.com/de6z1fqfs/image/upload/v1700031086/pizzaTop/products/pizzaCheese_fdgs47.jpg
    sizes:
      type: array
      items:
        $ref: "#/ProductPrice"

ProductPrice:
  type: object
  properties:
    size_name:
      type: string
      example: Small
    product_price:
      type: float
      example: 100000.00

CreateProductBody:
  type: object
  properties:
    productName:
      type: string
    productDesc:
      type: string
    category:
      type: string
      enum: [food, drink, topping]
    productImage:
      type: string
      format: binary

CreateProductResponse:
  type: object
  properties:
    product_name:
      type: string
    product_slug:
      type: string
    product_image:
      type: string
    product_desc:
      type: string
    category:
      type: string
      enum: [food, drink, topping]
    is_deleted:
      type: boolean
    product_id:
      type: integer
      format: int64

AddPriceProductResponse:
  type: object
  properties:
    product_id:
      type: integer
    product_size_id:
      type: integer
    product_price:
      type: float
    product_price_id:
      type: integer
